ignore:
  - "Pods/*"
  - "fastlane/*"
  - "bitrise.yml"
  - "get_latest_release_notes.sh"
  - "BaseAppV2UnitTests/*"
  - "BaseAppV2UITests/*"

comment:
  layout: "header, diff, changes"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  branches: null
