ignore:
  - "Pods/*"
  - "fastlane/*"
  - "bitrise.yml"
  - "get_latest_release_notes.sh"
  - "BaseAppV2UnitTests/*"
  - "BaseAppV2UITests/*"
  - "BaseAppV2IntegrationTests/*"
  - "CONTRIBUTING.md"
  - "PULL_REQUEST_TEMPLATE.md"

comment:
  layout: "header, diff, changes"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  branches: null
